name: end-to-end tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: cypress-io/github-action@d2b5039cb4888cf1f0bb9e808f904f7093e0cb2a
        with:
          build: npm run build
          start: npm run serve
          command: npm run e2e:visual
          record: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
